/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DataPointerRegistryInterface extends Interface {
  getFunction(nameOrSignature: "commit" | "pointerByMessage"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DataCommitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "commit",
    values: [BigNumberish, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "pointerByMessage",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "commit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pointerByMessage",
    data: BytesLike
  ): Result;
}

export namespace DataCommittedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    messageHash: BytesLike,
    cid: string
  ];
  export type OutputTuple = [tokenId: bigint, messageHash: string, cid: string];
  export interface OutputObject {
    tokenId: bigint;
    messageHash: string;
    cid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DataPointerRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DataPointerRegistry;
  waitForDeployment(): Promise<this>;

  interface: DataPointerRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  commit: TypedContractMethod<
    [tokenId: BigNumberish, messageHash: BytesLike, cid: string],
    [void],
    "nonpayable"
  >;

  pointerByMessage: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "commit"
  ): TypedContractMethod<
    [tokenId: BigNumberish, messageHash: BytesLike, cid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "pointerByMessage"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;

  getEvent(
    key: "DataCommitted"
  ): TypedContractEvent<
    DataCommittedEvent.InputTuple,
    DataCommittedEvent.OutputTuple,
    DataCommittedEvent.OutputObject
  >;

  filters: {
    "DataCommitted(uint256,bytes32,string)": TypedContractEvent<
      DataCommittedEvent.InputTuple,
      DataCommittedEvent.OutputTuple,
      DataCommittedEvent.OutputObject
    >;
    DataCommitted: TypedContractEvent<
      DataCommittedEvent.InputTuple,
      DataCommittedEvent.OutputTuple,
      DataCommittedEvent.OutputObject
    >;
  };
}
