/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chatPaySol from "./ChatPay.sol";
export type { chatPaySol };
import type * as hnftSol from "./HNFT.sol";
export type { hnftSol };
export type { ConsentRegistry } from "./ConsentRegistry";
export type { DataPointerRegistry } from "./DataPointerRegistry";
export type { TraitAttestor } from "./TraitAttestor";
