/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as chatPaySol from "./ChatPay.sol";
export * as hnftSol from "./HNFT.sol";
export { ConsentRegistry__factory } from "./ConsentRegistry__factory";
export { DataPointerRegistry__factory } from "./DataPointerRegistry__factory";
export { TraitAttestor__factory } from "./TraitAttestor__factory";
